import type { EpisodeEvent, MediaItem } from "@/shared/lib/types";

export const demoSeries: MediaItem[] = [
  {
    id: "demo-severance",
    slug: "severance",
    kind: "series",
    title: "Severance",
    spanishTitle: "Separación",
    synopsis:
      "En Lumon Industries, la memoria laboral y la vida personal están separadas por un procedimiento tan elegante como inquietante.",
    posterTone: "indigo",
    score: 8.7,
    platform: "Apple TV+",
    latamPlatform: "Apple TV+",
    country: "USA",
    genres: ["Drama", "Ciencia ficción", "Thriller"],
    season: "T2",
    totalEpisodes: 10,
    airedEpisodes: 8,
    watchedEpisodes: 8,
    premiereDate: "2026-08-03",
    finaleDate: "2026-09-28",
    status: "Renovada",
    imdbUrl: "https://www.imdb.com/title/tt11280740/",
    featured: true,
  },
  {
    id: "demo-penguin",
    slug: "the-penguin",
    kind: "series",
    title: "The Penguin",
    synopsis:
      "Oz Cobb asciende por el submundo de Gotham en una historia criminal de ambición, lealtades frágiles y poder.",
    posterTone: "amber",
    score: 8.6,
    platform: "MAX",
    latamPlatform: "MAX",
    country: "USA",
    genres: ["Drama", "Crimen"],
    season: "T1",
    totalEpisodes: 8,
    airedEpisodes: 8,
    watchedEpisodes: 8,
    premiereDate: "2026-07-12",
    finaleDate: "2026-08-30",
    status: "Miniserie",
  },
  {
    id: "demo-bear",
    slug: "the-bear",
    kind: "series",
    title: "The Bear",
    synopsis:
      "Una cocina, una familia improvisada y la presión por convertir el caos cotidiano en algo extraordinario.",
    posterTone: "crimson",
    score: 8.5,
    platform: "FX",
    latamPlatform: "Disney+",
    country: "USA",
    genres: ["Drama", "Comedia"],
    season: "T5",
    totalEpisodes: 10,
    airedEpisodes: 5,
    watchedEpisodes: 4,
    premiereDate: "2026-07-29",
    finaleDate: "2026-09-30",
    status: "En emisión",
  },
  {
    id: "demo-andor",
    slug: "andor",
    kind: "series",
    title: "Andor",
    synopsis:
      "La rebelión se construye con decisiones pequeñas, sacrificios enormes y personas que aún no saben que harán historia.",
    posterTone: "steel",
    score: 8.4,
    platform: "Disney+",
    country: "USA",
    genres: ["Drama", "Ciencia ficción"],
    season: "T2",
    totalEpisodes: 12,
    airedEpisodes: 12,
    watchedEpisodes: 10,
    premiereDate: "2026-04-22",
    finaleDate: "2026-07-08",
    status: "Finalizada",
  },
  {
    id: "demo-last-of-us",
    slug: "the-last-of-us",
    kind: "series",
    title: "The Last of Us",
    synopsis:
      "Dos supervivientes atraviesan un país roto mientras descubren que la esperanza también puede ser peligrosa.",
    posterTone: "moss",
    score: 8.7,
    platform: "HBO",
    latamPlatform: "MAX",
    country: "USA",
    genres: ["Drama", "Terror"],
    season: "T3",
    totalEpisodes: 9,
    airedEpisodes: 2,
    watchedEpisodes: 2,
    premiereDate: "2026-08-02",
    finaleDate: "2026-09-27",
    status: "En emisión",
  },
  {
    id: "demo-shogun",
    slug: "shogun",
    kind: "series",
    title: "Shōgun",
    synopsis:
      "El destino de Japón se cruza con la llegada de un navegante extranjero y una guerra política silenciosa.",
    posterTone: "vermillion",
    score: 8.6,
    platform: "FX",
    latamPlatform: "Disney+",
    country: "USA",
    genres: ["Drama", "Historia"],
    season: "T2",
    totalEpisodes: 10,
    airedEpisodes: 0,
    watchedEpisodes: 0,
    premiereDate: "2026-09-18",
    finaleDate: "2026-11-20",
    status: "Próximamente",
  },
];

export const demoMovies: MediaItem[] = [
  {
    id: "movie-afterlight",
    slug: "afterlight-2026",
    kind: "movie",
    title: "Afterlight",
    synopsis: "Una señal imposible obliga a una astrónoma a elegir entre la evidencia y todo aquello que ama.",
    posterTone: "violet",
    score: 8.1,
    platform: "Cines",
    country: "UK",
    genres: ["Ciencia ficción", "Drama"],
    releaseDate: "2026-09-10",
    releaseYear: 2026,
    releaseType: "Cines",
    releaseTags: ["Estreno"],
    director: "Mara Voss",
    cast: ["Elena Ruiz", "Theo James", "Jae Kim"],
    runtime: 128,
    status: "Próximamente",
  },
  {
    id: "movie-red-room",
    slug: "the-red-room-2026",
    kind: "movie",
    title: "The Red Room",
    synopsis: "Un thriller contenido sobre la obsesión, la identidad y el precio de mirar demasiado cerca.",
    posterTone: "ruby",
    score: 7.9,
    platform: "MUBI",
    country: "Francia",
    genres: ["Thriller"],
    releaseDate: "2026-08-21",
    releaseYear: 2026,
    releaseType: "Streaming",
    releaseTags: ["Estreno VOD"],
    streaming: "MUBI",
    director: "Claire Moreau",
    cast: ["Adèle Martin", "Louis Garrel"],
    runtime: 112,
    status: "Próximamente",
  },
  {
    id: "movie-horizon",
    slug: "blue-horizon-2026",
    kind: "movie",
    title: "Blue Horizon",
    synopsis: "Una historia íntima de segundas oportunidades en el último verano de una pequeña ciudad costera.",
    posterTone: "ocean",
    score: 7.7,
    platform: "Netflix",
    country: "España",
    genres: ["Drama"],
    releaseDate: "2026-10-02",
    releaseYear: 2026,
    releaseType: "Streaming",
    releaseTags: ["Adición a Catálogo"],
    streaming: "Netflix",
    director: "Lucía Ferrer",
    cast: ["Álvaro Morte", "María Pedraza"],
    runtime: 104,
    status: "Próximamente",
  },
];

export const demoEpisodes: EpisodeEvent[] = [
  { id: "ep-1", seriesSlug: "severance", title: "Severance", episode: "T2 · E08", date: "2026-08-03", platform: "Apple TV+", posterTone: "indigo" },
  { id: "ep-2", seriesSlug: "the-bear", title: "The Bear", episode: "T5 · E02", date: "2026-08-04", platform: "Disney+", posterTone: "crimson" },
  { id: "ep-3", seriesSlug: "the-last-of-us", title: "The Last of Us", episode: "T3 · E02", date: "2026-08-04", platform: "MAX", posterTone: "moss" },
  { id: "ep-4", seriesSlug: "the-bear", title: "The Bear", episode: "T5 · E03", date: "2026-08-11", platform: "Disney+", posterTone: "crimson" },
  { id: "ep-5", seriesSlug: "severance", title: "Severance", episode: "T2 · E09", date: "2026-08-10", platform: "Apple TV+", posterTone: "indigo" },
  { id: "ep-6", seriesSlug: "the-penguin", title: "The Penguin", episode: "T1 · E08", date: "2026-08-30", platform: "MAX", posterTone: "amber", tags: ["Final de Temporada"] },
];
